name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/azure-static-web-apps-orange-sand-06ce10203.yml
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # specify Node.js version here

      - name: Install dependencies
        run: npm install --prefix frontend

      - name: Build
        run: npm run build --prefix frontend

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_SAND_06CE10203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Provides GitHub token for authentication
          action: "upload"
          ###### Repository/Build Configurations - These fields are configured during the Azure SWA setup
          app_location: "frontend" # Location for the source code of your app
          api_location: "" # No API for static frontend
          skip_api_build: true
          output_location: "dist" # Build output directory

